---
title: "Win Big Results"
# author: "Jeffrey M. Pisklak"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: false
bibliography: references.bib
csl: apa-with-abstract.csl

nocite: |
  @R
---

<!-- https://www.w3schools.com/tags/tag_details.asp -->
<style>
details > summary {
  padding: 4px;
  cursor: pointer;
  font-size: 1.5em;
}

h1.title{font-weight: bold; font-size: 3em}
h1{text-align: left; font-weight: bold; font-size: 2.5em}
h2{text-align: left; font-weight: bold; font-size: 2em}
h3{text-align: left; font-size: 2em}
h4{text-align: left; font-size: 1.5em}

</style>

```{r setup, include = FALSE}
options(pillar.print_max = Inf)

if (!require(knitr)) {
  install.packages("knitr")
}
if (!require(kableExtra)) {
  install.packages("kableExtra")
}
if (!require(tidyverse)) {
  install.packages("tidyverse")
}

library(knitr)
library(kableExtra)
library(tidyverse)

# Directory
# opts_knit$set(root.dir = dirname(getwd())) #Rendering from this .Rmd file.
opts_knit$set(root.dir = main_dir) # Rendering from generate_markdown.R

opts_chunk$set(
  echo = FALSE,
  # include = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.width = 7, fig.height = 5
)
```

# Experiment 1a

<!-- Participant Information -->
```{r child = 'markdown/exp-1a/subject_info.Rmd'}
```

<br>

---

<br>

<!-- Catch Trials -->
```{r child = 'markdown/exp-1a/catch_trials.Rmd'}
```

<br>

---

<br>

<!-- Risk Pref Trials -->
```{r child = 'markdown/exp-1a/risky_trials.Rmd'}
```

<br>

---

<br>

# Experiment 1b

<!-- Participant Information -->
```{r child = 'markdown/exp-1b/subject_info.Rmd'}
```

<br>

---

<br>


<!-- Catch Trials -->
```{r child = 'markdown/exp-1b/catch_trials.Rmd'}
```

<br>

---

<br>

<!-- Risk Pref Trials -->
```{r child = 'markdown/exp-1b/risky_trials.Rmd'}
```

<br>

---

<br>

